Redo autoconf
ESMCI/mpi-serial pull request #26
Opened 2023-12-22 21:56 UTC by jedwards4b

Redo autoconf build system to be more standard.

2023-12-25 20:01 UTC, gold2718 requested changes
There seem to be a lot of changes that are unrelated to the stated purpose of this PR (redo autoconf). If that is a correct assessment, it would be helpful to add those items to the PR description or move these changes to a different branch for later inclusion (some seems unfinished, much is commented out).

2023-12-25 20:01 UTC, gold2718 commented on configure.ac
> +#AC_LANG_POP(Fortran)
?? Is this needed?

2023-12-25 20:01 UTC, gold2718 commented on COPYING
> +/glade/u/apps/derecho/23.09/spack/opt/spack/automake/1.16.5/gcc/7.5.0/kd7y/share/automake-1.16/COPYING
I really don't understand all these files with specific Derecho path names. Please explain (in the PR conversation would be best since the PR says it is to make autoconf more standard and this does not feel very standardized).
This comment and request goes for all the files with these Derecho paths.

2023-12-25 20:01 UTC, gold2718 commented on recv.c
> +//    printf("mpi_match_send %d %d\n",*(int *)tag, ((Req *) r)->tag);
Remove debug print?

2023-12-25 20:01 UTC, gold2718 commented on send.c
> +//    printf("mpi_match_recv %d %d\n",*((int *) tag), ((Req *)r)->tag);
Remove debug print?

2023-12-25 20:01 UTC, gold2718 commented on send.c
> +//      printf("calling copy datatype %d %d %d %d\n",(int) datatype, count, rreq->type, rreq->count);
Remove debug print?

2023-12-25 20:01 UTC, gold2718 commented on tests/Makefile.in
Why is this in the repo? If we are supposed to use autoconf and automake to generate Makefiles, why store generated code?

2023-12-25 20:01 UTC, gold2718 commented on tests/ctest.c
> +#else
What is this all about?

2023-12-25 20:01 UTC, gold2718 commented on tests/ftest.F90
> +!          disps(i) = 1 + (i * 2)
remove?

2023-12-25 20:01 UTC, gold2718 commented on type.c
> +
Not sure what is going on here. Does this need finishing or removing? Is it even related to the description of this PR (redo autoconf)?

2023-12-25 20:01 UTC, gold2718 commented on type.c
> +*/
This is an awful lot of commented out code. Is it needed? Should it be kept with some sort of testing or debug `#ifdef`? Does it have anything to do with the subject of this PR (redo autoconf)?

2023-12-25 20:01 UTC, gold2718 commented on configure
Why is this in the repo? If we are supposed to use autoconf to generate configure, why store generated code?

2023-12-25 20:01 UTC, gold2718 commented on Makefile
Why is this in the repo? If we are supposed to use autoconf and automake to generate Makefiles, why store generated code?

2023-12-25 20:01 UTC, gold2718 commented on aclocal.m4
Full confession, I never really understood these files. They are so full of convolutions to make everything work all the time. It seems to work so . . .

2023-12-26 14:27 UTC, jedwards4b commented
Those changes were removed in the previous PR - this one just needed to be merged to master.

2023-12-27 11:15 UTC, gold2718 commented
> Those changes were removed in the previous PR - this one just needed to be merged to master.

Thanks, it can be hard to figure out what the code will look like when the PR is against an old hash.

2023-12-27 11:24 UTC, gold2718 approved these changes
Have you tested an install?
I am approving but it would be nice to know what testing has been done (besides `make tests` which I sure hope was run).

2023-12-27 14:51 UTC, merged

2023-12-27 14:52 UTC, jedwards4b commented
I have tested on derecho, using spack on derecho and the github action is also installing and running make check.  thank you

2023-12-28 01:41 UTC, rljacob commented on COPYING
> +                    GNU GENERAL PUBLIC LICENSE
What is the purpose of a file called COPYING with the GPL in it?  This software is covered by the BSD 3-clause.

2023-12-28 13:58 UTC, jedwards4b commented on COPYING
> +                    GNU GENERAL PUBLIC LICENSE
This file was generated by automake and I didn't look at it too closely.   I will correct.